import { Badge, Button, Empty, Expiry, Field, labels } from './InventoryUI'
import { dateTime, money, number } from '../../services/inventoryCalculations'

export const defaultFilters = { search: '', category: '', supplier: '', location: '', status: '', expiry: '', sort: 'name', active: 'active' }
export function InventoryToolbar({ items, filters, setFilters }) {
  const set = key => e => setFilters({ ...filters, [key]: e.target.value })
  const choices = key => [...new Set(items.map(i => i[key]).filter(Boolean))].sort((a, b) => a.localeCompare(b, 'vi'))
  return <section className="inv-panel"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Field label="Tìm tên, SKU, hãng, nhà cung cấp" type="search" placeholder="Ví dụ: sua, tra lai…" value={filters.search} onChange={set('search')} />{[['category', 'Nhóm hàng'], ['supplier', 'Nhà cung cấp'], ['location', 'Vị trí lưu kho']].map(([key, label]) => <Field key={key} label={label} value={filters[key]} onChange={set(key)}><option value="">Tất cả</option>{choices(key === 'location' ? 'storageLocation' : key).map(value => <option key={value}>{value}</option>)}</Field>)}<Field label="Trạng thái tồn" value={filters.status} onChange={set('status')}><option value="">Tất cả</option>{['NORMAL', 'LOW_STOCK', 'OUT_OF_STOCK'].map(s => <option key={s} value={s}>{labels[s]}</option>)}</Field><Field label="Hạn sử dụng" value={filters.expiry} onChange={set('expiry')}><option value="">Tất cả</option>{['EXPIRED', 'EXPIRING_SOON', 'EXPIRING_30_DAYS', 'SAFE', 'NO_EXPIRY'].map(s => <option key={s} value={s}>{labels[s]}</option>)}</Field><Field label="Sắp xếp" value={filters.sort} onChange={set('sort')}>{Object.entries({ name: 'Tên A–Z', stock: 'Tồn thấp nhất', value: 'Giá trị tồn cao nhất', expiry: 'Hạn gần nhất', updated: 'Cập nhật gần nhất' }).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</Field><Field label="Theo dõi" value={filters.active} onChange={set('active')}><option value="active">Đang theo dõi</option><option value="inactive">Đã ngừng</option><option value="all">Tất cả</option></Field></div><Button className="mt-3" onClick={() => setFilters({ ...defaultFilters })}>Xóa bộ lọc</Button></section>
}
function Actions({ item, onAction }) {
  return <Field label={`Thao tác · ${item.name}`} value="" onChange={e => { if (e.target.value) onAction(e.target.value, item.id) }}><option value="">Chọn tác vụ</option><option value="detail">Xem chi tiết</option>{item.active && <><option value="import">Nhập thêm</option><option value="export">Xuất kho</option><option value="count">Kiểm kho</option></>}<option value="edit">Chỉnh thông tin</option><option value="active">{item.active ? 'Ngừng theo dõi' : 'Theo dõi trở lại'}</option></Field>
}
function Stock({ item }) {
  return <div className="min-w-24"><strong>{number(item.currentStock)}</strong><div className="my-1 h-1.5 overflow-hidden rounded-full bg-stone-100" role="progressbar" aria-label={`Tồn so với định mức ${item.name}`} aria-valuemin={0} aria-valuemax={100} aria-valuenow={Math.min(100, Math.round(item.currentStock / (item.monthlyTargetQty || 1) * 100))}><div className="h-full rounded-full bg-[#B48660]" style={{ width: `${Math.min(100, item.currentStock / (item.monthlyTargetQty || 1) * 100)}%` }} /></div><small className="text-stone-500">Định mức {number(item.monthlyTargetQty)}</small></div>
}
export function InventoryList({ items, onAction }) {
  if (!items.length) return <Empty>Không có nguyên liệu phù hợp. Thử xóa bộ lọc hoặc thêm nguyên liệu.</Empty>
  return <><div className="inv-table-wrap hidden md:block"><table className="inv-table"><thead><tr>{['Nguyên liệu', 'SKU', 'Nhóm hàng', 'Hãng', 'Quy cách', 'Nhà cung cấp', 'Tồn hiện tại', 'Đơn vị', 'Tối thiểu', 'Lô gần hết hạn', 'Giá trị tồn', 'Trạng thái', 'Cập nhật', 'Thao tác'].map(h => <th key={h}>{h}</th>)}</tr></thead><tbody>{items.map(item => <tr key={item.id}><td><button className="text-left font-bold underline decoration-stone-200 underline-offset-4" onClick={() => onAction('detail', item.id)}>{item.name}</button>{!item.active && <small className="block">Đã ngừng</small>}</td><td>{item.sku}</td><td>{item.category}</td><td>{item.brand || '—'}</td><td>{item.packSize || '—'}</td><td>{item.supplier || 'Chưa xác định'}</td><td><Stock item={item} /></td><td>{item.baseUnit}</td><td>{number(item.minimumStock)}</td><td>{item.nearest?.batchCode && <small className="block">{item.nearest.batchCode}</small>}<Expiry value={item.nearest?.expiryDate} /></td><td className="whitespace-nowrap font-semibold">{money(item.inventoryValue)}</td><td><Badge status={item.status} /></td><td>{dateTime(item.updatedAt)}</td><td><Actions item={item} onAction={onAction} /></td></tr>)}</tbody></table></div><div className="grid gap-3 md:hidden">{items.map(item => <article className="inv-panel" key={item.id}><div className="flex items-start justify-between gap-2"><button className="text-left font-bold" onClick={() => onAction('detail', item.id)}>{item.name}<small className="block font-normal text-stone-500">{item.sku} · {item.category}</small></button><Badge status={item.status} /></div><p className="inv-help">{item.brand} · {item.packSize} · {item.supplier || 'Chưa có nhà cung cấp'}</p><div className="my-3 flex items-center justify-between gap-3"><Stock item={item} /><strong>{money(item.inventoryValue)}</strong></div><p className="inv-help">Đơn vị: {item.baseUnit} · Tối thiểu: {number(item.minimumStock)}</p><Expiry value={item.nearest?.expiryDate} /><p className="inv-help">Cập nhật: {dateTime(item.updatedAt)}</p><Actions item={item} onAction={onAction} /></article>)}</div></>
}
