import { useState } from 'react'
import { dateTime, money, number } from '../../services/inventoryCalculations'
import { Badge, Button, Dialog, Empty, Expiry, Field, FormFooter, labels } from './InventoryUI'

export function InventoryHistory({ state, itemId }) {
  const [query, setQuery] = useState('')
  const names = Object.fromEntries(state.items.map(i => [i.id, i.name]))
  const rows = [...state.transactions, ...state.audit].filter(t => (!itemId || t.itemId === itemId) && (!query || t.type === query)).sort((a, b) => b.occurredAt.localeCompare(a.occurredAt))
  const [limit, setLimit] = useState(50)
  return <div><Field label="Loại giao dịch" value={query} onChange={e => { setQuery(e.target.value); setLimit(50) }}><option value="">Tất cả (gồm sửa thông tin)</option>{['IMPORT', 'EXPORT', 'COUNT', 'ADJUST_IN', 'ADJUST_OUT', 'DISCARD', 'RETURN'].map(type => <option key={type} value={type}>{labels[type]}</option>)}</Field><div className="mt-4 space-y-3">{rows.slice(0, limit).map(row => <article key={row.id} className="inv-panel"><div className="flex flex-wrap justify-between gap-2"><strong>{labels[row.type] || 'Cập nhật thông tin'} · {names[row.itemId]}</strong><time>{dateTime(row.occurredAt)}</time></div>{row.quantity != null && <p>Số lượng: {number(row.quantity)} · Giá: {money(row.unitCost)}</p>}{row.stockBefore != null && <p>Tồn: {number(row.stockBefore)} → {number(row.stockAfter)}</p>}<p>{row.reason || '—'}{row.note && ` · ${row.note}`}</p><small>Người thao tác: {row.createdBy || 'Không ghi tên'}{row.batchId && ` · Lô: ${state.batches.find(b => b.id === row.batchId)?.batchCode || row.batchId}`}</small></article>)}{!rows.length && <Empty>Chưa có lịch sử.</Empty>}{rows.length > limit && <Button onClick={() => setLimit(limit + 50)}>Xem thêm ({rows.length - limit})</Button>}</div></div>
}
export function InventoryItemDrawer({ item, state, onClose, onAction, onSave }) {
  const [tab, setTab] = useState('overview')
  const [expiryBatch, setExpiryBatch] = useState(null)
  const [expiryDate, setExpiryDate] = useState('')
  const [reason, setReason] = useState('')
  const [error, setError] = useState('')
  const counts = state.counts.filter(c => c.itemId === item.id).sort((a, b) => b.countedAt.localeCompare(a.countedAt))
  const lastImport = item.batches.slice().sort((a, b) => b.receivedAt.localeCompare(a.receivedAt))[0]
  const overview = { SKU: item.sku, 'Nhóm hàng': item.category, Hãng: item.brand, 'Quy cách': item.packSize, 'Đơn vị': item.baseUnit, 'Quy đổi tham khảo': `${number(item.conversionRate)} ${item.contentUnit || ''}`, 'Đơn giá dự kiến': money(item.unitPrice), 'Định mức tháng': number(item.monthlyTargetQty), 'Tồn tối thiểu': number(item.minimumStock), 'Điểm đặt hàng': number(item.reorderPoint), 'Nhà cung cấp': item.supplier, 'Nhóm nguồn Excel': item.sourceGroup, 'Vị trí': item.storageLocation, 'Nhập gần nhất': dateTime(lastImport?.receivedAt), 'Kiểm gần nhất': dateTime(counts.find(c => c.status === 'CONFIRMED')?.countedAt) }
  return <Dialog title={item.name} drawer onClose={onClose}><div className="mb-5 flex flex-wrap items-center gap-3"><Badge status={item.status} /><strong>{number(item.currentStock)} {item.baseUnit} · {money(item.inventoryValue)}</strong></div><div className="inv-tabs">{Object.entries({ overview: 'Tổng quan', batches: 'Các lô hàng', history: 'Lịch sử', counts: 'Kiểm kho' }).map(([key, label]) => <Button key={key} primary={tab === key} aria-pressed={tab === key} onClick={() => setTab(key)}>{label}</Button>)}</div>
    {tab === 'overview' && <><dl className="grid grid-cols-2 gap-4">{Object.entries(overview).map(([label, value]) => <div key={label}><dt className="text-xs text-stone-500">{label}</dt><dd className="mt-1 break-words font-semibold">{value || '—'}</dd></div>)}</dl><div className="mt-5 flex flex-wrap gap-2">{item.active && <><Button primary onClick={() => onAction('import', item.id)}>Nhập thêm</Button><Button onClick={() => onAction('export', item.id)}>Xuất kho</Button><Button onClick={() => onAction('count', item.id)}>Kiểm kho</Button></>}<Button onClick={() => onAction('edit', item.id)}>Chỉnh thông tin</Button></div></>}
    {tab === 'batches' && <div className="space-y-4">{item.batches.map(b => <section className="inv-panel" key={b.id}><strong>{b.batchCode}</strong><p className="my-2">Nhập {number(b.receivedQuantity)} · Còn {number(b.remainingQuantity)} · Giá {money(b.unitCost)}</p><Expiry value={b.expiryDate} /><p className="mt-2 text-sm">Nhập: {dateTime(b.receivedAt)}<br />Sản xuất: {b.manufactureDate ? new Date(b.manufactureDate).toLocaleDateString('vi-VN', { timeZone: 'UTC' }) : '—'}<br />Nhà cung cấp: {b.supplier || '—'}<br />Hóa đơn: {b.invoiceCode || '—'}<br />Ghi chú: {b.note || '—'}<br />Người nhập: {b.createdBy || '—'}</p><Button className="mt-3" onClick={() => { setExpiryBatch(b); setExpiryDate(b.expiryDate?.slice(0, 10) || ''); setReason(''); setError('') }}>Sửa / xóa hạn sử dụng</Button></section>)}{!item.batches.length && <Empty>Chưa từng nhập hàng.</Empty>}</div>}
    {tab === 'history' && <InventoryHistory state={state} itemId={item.id} />}
    {tab === 'counts' && <div className="space-y-3">{counts.map(c => <article className="inv-panel" key={c.id}><strong>{c.status === 'DRAFT' ? 'Nháp' : 'Đã xác nhận'} · {dateTime(c.countedAt)}</strong><p>Hệ thống {number(c.systemQuantity)} → Thực tế {number(c.actualQuantity)}</p><p>Chênh lệch {number(c.difference)} · {money(c.differenceValue)}</p><p>{c.reason} · {c.countedBy || 'Không ghi tên'}</p>{c.status === 'DRAFT' && <Button onClick={() => onAction('count', item.id)}>Tiếp tục kiểm</Button>}</article>)}{!counts.length && <Empty>Chưa có phiếu kiểm.</Empty>}</div>}
    {expiryBatch && <Dialog title={`Xác nhận sửa hạn · ${expiryBatch.batchCode}`} onClose={() => setExpiryBatch(null)}><form onSubmit={e => { e.preventDefault(); try { onSave('EXPIRY', { batchId: expiryBatch.id, expiryDate, reason }, false); setExpiryBatch(null) } catch (err) { setError(err.message) } }}><p className="inv-help">Để trống ngày để xóa riêng hạn sử dụng. Lô và số lượng vẫn được giữ, thao tác được ghi lịch sử.</p><Field label="Hạn sử dụng" type="date" value={expiryDate} onChange={e => setExpiryDate(e.target.value)} /><Button className="my-3" onClick={() => setExpiryDate('')}>Xóa ngày</Button><Field label="Lý do sửa / xóa" required value={reason} onChange={e => setReason(e.target.value)} />{error && <p className="inv-error" role="alert">{error}</p>}<FormFooter onClose={() => setExpiryBatch(null)} label="Xác nhận sửa hạn" /></form></Dialog>}
  </Dialog>
}
