import { useMemo, useState } from 'react'
import { allocation, money, normalize, number, round } from '../../services/inventoryCalculations'
import { categories } from '../../data/inventorySeed'
import { Button, Dialog, Empty, Expiry, Field, FormFooter } from './InventoryUI'

const nowInput = () => { const d = new Date(); return new Date(d.getTime() - d.getTimezoneOffset() * 60000).toISOString().slice(0, 16) }
const inputNumber = { type: 'number', min: '0', max: '1000000000000', step: 'any', required: true }
function ItemSelect({ items, value, onChange }) {
  return <Field label="Nguyên liệu" value={value} onChange={onChange} required><option value="">Chọn nguyên liệu</option>{items.filter(i => i.active).map(i => <option key={i.id} value={i.id}>{i.name} · {i.sku} · {i.packSize}</option>)}</Field>
}
export function StockImportDialog({ items, initialItem, initialRows, planId, onSave, onClose }) {
  const makeRow = itemId => ({ key: crypto.randomUUID(), itemId: itemId || '', quantity: '', unitCost: items.find(i => i.id === itemId)?.unitPrice ?? '', batchCode: '', supplier: items.find(i => i.id === itemId)?.supplier || '', manufactureDate: '', expiryDate: '' })
  const [rows, setRows] = useState(() => initialRows ? initialRows.map(row => ({ ...makeRow(row.itemId), quantity: row.quantity })) : [makeRow(initialItem)])
  const [common, setCommon] = useState({ occurredAt: nowInput(), invoiceCode: '', note: '', createdBy: '' })
  const [error, setError] = useState('')
  const update = (key, patch) => setRows(old => old.map(row => row.key === key ? { ...row, ...patch } : row))
  return <Dialog title="Nhập hàng theo lô" onClose={onClose}><form onSubmit={e => { e.preventDefault(); setError(''); try { onSave('IMPORT', { ...common, rows, planId }) } catch (err) { setError(err.message) } }}>
    <p className="inv-help">Số lượng và giá tính theo 1 đơn vị mua (quy cách hiển thị). Mỗi dòng tạo một lô riêng.</p>
    <div className="inv-grid">{[['occurredAt', 'Ngày giờ nhập', 'datetime-local'], ['invoiceCode', 'Mã hóa đơn', 'text'], ['createdBy', 'Người thao tác', 'text'], ['note', 'Ghi chú', 'text']].map(([key, label, type]) => <Field key={key} label={label} type={type} required={key === 'occurredAt'} value={common[key]} onChange={e => setCommon({ ...common, [key]: e.target.value })} />)}</div>
    <div className="mt-5 space-y-4">{rows.map((row, index) => { const item = items.find(i => i.id === row.itemId); const dateError = row.expiryDate && row.manufactureDate && row.expiryDate < row.manufactureDate; return <section className="inv-panel" key={row.key}><div className="mb-3 flex items-center justify-between"><h3 className="font-bold">Lô {index + 1}</h3>{rows.length > 1 && <Button onClick={() => setRows(rows.filter(r => r.key !== row.key))}>Bỏ dòng</Button>}</div>
      <div className="inv-grid"><ItemSelect items={items} value={row.itemId} onChange={e => update(row.key, { ...makeRow(e.target.value), key: row.key })} /><Field label="Mã lô (tự sinh nếu bỏ trống)" value={row.batchCode} onChange={e => update(row.key, { batchCode: e.target.value })} /><Field label={`Số lượng · ${item?.baseUnit || 'đơn vị mua'} (${item?.packSize || '—'})`} {...inputNumber} min="0.000001" value={row.quantity} onChange={e => update(row.key, { quantity: e.target.value })} /><Field label="Giá / đơn vị mua (₫)" {...inputNumber} value={row.unitCost} onChange={e => update(row.key, { unitCost: e.target.value })} /><Field label="Ngày sản xuất" type="date" value={row.manufactureDate} onChange={e => update(row.key, { manufactureDate: e.target.value })} /><Field label="Hạn sử dụng" type="date" min={row.manufactureDate || undefined} error={dateError ? 'Hạn phải từ ngày sản xuất trở đi.' : ''} value={row.expiryDate} onChange={e => update(row.key, { expiryDate: e.target.value })} /><Field label="Nhà cung cấp" value={row.supplier} onChange={e => update(row.key, { supplier: e.target.value })} /></div></section> })}</div>
    <div className="mt-4 flex flex-wrap items-center justify-between gap-3"><Button onClick={() => setRows([...rows, makeRow('')])}>+ Thêm nguyên liệu</Button><strong>Tổng phiếu: {money(rows.reduce((sum, row) => sum + Number(row.quantity) * Number(row.unitCost), 0))}</strong></div>
    {error && <p role="alert" className="inv-error">{error}</p>}<FormFooter onClose={onClose} label="Xác nhận nhập kho" />
  </form></Dialog>
}
export function StockExportDialog({ items, batches, initialItem, onSave, onClose }) {
  const [form, setForm] = useState({ itemId: initialItem || '', quantity: '', purpose: 'use', occurredAt: nowInput(), note: '', createdBy: '' })
  const [error, setError] = useState('')
  const purposes = { use: 'Sử dụng pha chế', expired: 'Hủy do hết hạn', damaged: 'Hư hỏng', supplier: 'Trả nhà cung cấp', other: 'Điều chỉnh khác' }
  const item = items.find(i => i.id === form.itemId)
  const preview = useMemo(() => { try { return { rows: allocation(batches, form.itemId, Number(form.quantity)) } } catch (err) { return { rows: [], error: err.message } } }, [batches, form.itemId, form.quantity])
  const set = key => e => setForm({ ...form, [key]: e.target.value })
  return <Dialog title="Xuất kho · FEFO / FIFO" onClose={onClose}><form onSubmit={e => { e.preventDefault(); try { onSave('EXPORT', { ...form, reason: purposes[form.purpose] }) } catch (err) { setError(err.message) } }}><div className="inv-grid"><ItemSelect items={items} value={form.itemId} onChange={set('itemId')} /><Field label={`Số lượng xuất (tồn ${number(item?.currentStock)} · ${item?.packSize || '—'})`} {...inputNumber} min="0.000001" max={item?.currentStock || 0} value={form.quantity} error={preview.error} onChange={set('quantity')} /><Field label="Mục đích" value={form.purpose} onChange={set('purpose')}>{Object.entries(purposes).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</Field><Field label="Ngày giờ" type="datetime-local" required value={form.occurredAt} onChange={set('occurredAt')} /><Field label="Người thao tác" value={form.createdBy} onChange={set('createdBy')} /><Field label="Ghi chú / lý do chi tiết" required={form.purpose === 'other'} value={form.note} onChange={set('note')} /></div>
    <h3 className="mb-3 mt-5 font-bold">Các lô sẽ bị trừ</h3><p className="inv-help">Ưu tiên hạn gần nhất; lô không có hạn dùng ngày nhập trước. Lô hết hạn vẫn được hiển thị để xử lý hủy.</p>{preview.rows.length ? preview.rows.map(b => <div key={b.id} className="inv-panel mb-2 flex flex-wrap justify-between gap-3"><div><strong>{b.batchCode}</strong><p>Xuất {number(b.quantity)} · {money(b.quantity * b.unitCost)}</p></div><Expiry value={b.expiryDate} /></div>) : <Empty>Chọn nguyên liệu và số lượng hợp lệ để xem trước.</Empty>}
    {error && <p role="alert" className="inv-error">{error}</p>}<FormFooter onClose={onClose} label="Xác nhận xuất kho" /></form></Dialog>
}
export function StockCountDialog({ items, counts, initialItem, onSave, onClose }) {
  const [query, setQuery] = useState('')
  const [actor, setActor] = useState('')
  const [rows, setRows] = useState(() => Object.fromEntries(counts.filter(c => c.status === 'DRAFT' && (!initialItem || c.itemId === initialItem)).map(c => [c.itemId, { id: c.id, actualQuantity: c.actualQuantity, reason: c.reason }])))
  const [error, setError] = useState('')
  const visible = items.filter(i => i.active && (!initialItem || i.id === initialItem) && i.search.includes(normalize(query)))
  const selected = Object.entries(rows).filter(([, row]) => row.actualQuantity !== '' && row.actualQuantity != null).map(([itemId, row]) => ({ ...row, itemId }))
  function save(confirmed) { try { onSave('COUNT', { rows: selected, confirmed, createdBy: actor }) } catch (err) { setError(err.message) } }
  return <Dialog title="Kiểm kho thực tế" onClose={onClose}><form onSubmit={e => { e.preventDefault(); save(true) }}><div className="inv-grid"><Field label="Tìm nguyên liệu" value={query} onChange={e => setQuery(e.target.value)} /><Field label="Người kiểm" value={actor} onChange={e => setActor(e.target.value)} /></div><p className="inv-help">Để trống = chưa kiểm; nhập 0 = đã kiểm và hết hàng. Nháp được giữ khi đóng và tải lại. Khi xác nhận, chênh lệch được tính lại theo tồn hiện tại.</p><p className="mb-3 font-bold">Đã nhập {selected.length} / {items.filter(i => i.active && (!initialItem || i.id === initialItem)).length} nguyên liệu</p>
    <div className="max-h-[50vh] space-y-3 overflow-y-auto">{visible.map(item => { const row = rows[item.id] || { actualQuantity: '', reason: '' }; const diff = row.actualQuantity === '' ? null : round(Number(row.actualQuantity) - item.currentStock); const cost = item.currentStock ? item.inventoryValue / item.currentStock : item.unitPrice; const patch = value => setRows({ ...rows, [item.id]: { ...row, ...value } }); return <section className="inv-panel" key={item.id}><strong>{item.name}</strong><p className="inv-help">{item.sku} · {item.packSize} · Hệ thống: {number(item.currentStock)} · {diff === null ? 'Chưa kiểm' : `Chênh lệch: ${number(diff)} (${money(diff * cost)} ước tính)`}</p><div className="inv-grid"><Field label={`Tồn thực tế · ${item.name}`} {...inputNumber} required={false} value={row.actualQuantity} onChange={e => patch({ actualQuantity: e.target.value })} /><Field label="Lý do chênh lệch" value={row.reason} onChange={e => patch({ reason: e.target.value })} /></div></section> })}{!visible.length && <Empty />}</div>
    {error && <p role="alert" className="inv-error">{error}</p>}<FormFooter onClose={onClose} label="Xác nhận & điều chỉnh tồn" extra={<Button onClick={() => save(false)}>Lưu nháp</Button>} /></form></Dialog>
}
export function ItemDialog({ item, onSave, onClose }) {
  const [form, setForm] = useState(() => item ? { ...item } : { name: '', category: categories[0], supplier: '', brand: '', packSize: '', baseUnit: 'đơn vị mua', contentUnit: '', conversionRate: 1, unitPrice: 0, monthlyTargetQty: 0, minimumStock: 0, reorderPoint: 0, storageLocation: '' })
  const [error, setError] = useState('')
  const fields = { name: 'Tên nguyên liệu', brand: 'Hãng', supplier: 'Nhà cung cấp', packSize: 'Quy cách gốc', baseUnit: 'Đơn vị theo dõi', conversionRate: 'Lượng trong 1 đơn vị mua', contentUnit: 'Đơn vị quy đổi (g, ml, cái...)', unitPrice: 'Đơn giá / đơn vị mua (₫)', monthlyTargetQty: 'Định mức tháng (đơn vị mua)', minimumStock: 'Tồn tối thiểu', reorderPoint: 'Điểm đặt hàng', storageLocation: 'Vị trí lưu kho' }
  const numeric = ['conversionRate', 'unitPrice', 'monthlyTargetQty', 'minimumStock', 'reorderPoint']
  return <Dialog title={item ? `Chỉnh nguyên liệu · ${item.sku}` : 'Thêm nguyên liệu'} onClose={onClose}><form onSubmit={e => { e.preventDefault(); try { onSave('ITEM', form) } catch (err) { setError(err.message) } }}><p className="inv-help">Tồn được tính từ lô. Sau khi tạo nguyên liệu, nhập hàng hoặc kiểm kho để ghi nhận tồn thực tế.</p><div className="inv-grid"><Field label="Nhóm hàng" value={form.category} onChange={e => setForm({ ...form, category: e.target.value })}>{[...new Set([...categories, form.category])].map(c => <option key={c}>{c}</option>)}</Field>{Object.entries(fields).map(([key, label]) => <Field key={key} label={label} {...(numeric.includes(key) ? inputNumber : {})} required={numeric.includes(key) || ['name', 'baseUnit'].includes(key)} disabled={!!item?.batches?.length && ['baseUnit', 'conversionRate', 'packSize'].includes(key)} value={form[key] || (numeric.includes(key) ? 0 : '')} onChange={e => setForm({ ...form, [key]: e.target.value })} />)}</div>{error && <p role="alert" className="inv-error">{error}</p>}<FormFooter onClose={onClose} /></form></Dialog>
}
